++ 1.1 - **Software**

+++ 1.1.1 Micro-controller
++++ 1.1.1.1 - Sail motor control
++++ 1.1.1.2 - Rudder motor control
++++ 1.1.1.3 - Vessel Velocity
++++ 1.1.1.4 - Wind direction
++++ 1.1.1.5 - Vessel Orientation
++++ 1.1.1.6 - Vessel Global Position
++++ 1.1.1.7 - Communication network


+++ 1.1.2 - SBC Boat
++++ 1.1.2.1 - [FS] Sensor malfunction
++++ 1.1.2.2 - Wind to sail 
++++ 1.1.2.3 - Rudder path PID
++++ 1.1.2.4 - Data-logging
++++ 1.1.2.5 - Data steam transceiver


+++ 1.1.3 - SBC Land
++++ 1.1.3.1 - Fail-safe signal control
++++ 1.1.3.2 - Data visualisation

+++ 1.1.4 - Simulation
++++ 1.1.4.1 - Realistic sensor data
++++ 1.1.4.2 - Rudder path PID
++++ 1.1.4.3 - Wind to Sail 
++++ 1.1.4.4 - Vessel Orientation
++++ 1.1.4.5 - Vessel Position
++++ 1.1.4.6 - Wind direction
