++ Software

+++ Microcontroller
++++ Motor data <<TBD>>
++++ Orientation
++++ Position
++++ Wind speed
++++ Wind direction
++++ Rudder control
++++ Rudder position
++++ Velocity
++++ Sail control
++++ Sail position

+++ SBC Boat

++++ Angular motor control
++++ Data-logging
++++ Fail-safe sensor malfunction
++++ Fail-safe battery temperature
++++ Reliable data transceiver
++++ Data steam transceiver
++++ Future SBC for VISION/AI 

+++ BMS
++++ Power consumption <<TBD>>
++++ Battery temperature <<TBD>>
++++ State of Charge <<TBD>>

+++ SBC Land
++++ Data-logging
++++ Data stream transceiver
++++ Fail-safe signal control
++++ Data visualisation

+++ Simulation
++++ Path planning <<TBD>>
++++ Orientation
++++ Position
++++ Wind direction
