++ Hardware

+++ Sensor System
++++ Battery System
++++ RC Control
++++ Assembly
+++++ Modify Boxes
+++++ Build Wind Sensor and Mounts
+++++ Install and Connect

+++ Test Boat
++++ Battery System
++++ Fail Safe System
++++ Motor Control System
++++ Assembly and Mounts

+++ Large Boat
++++ Battery System
++++ Fail Safe System
++++ Motor Control System
++++ Assembly and Mounts