++ Hardware

+++ Construction
++++ Find waterproof containers
++++ Modify Containers for outgoing cables
++++ Install hardware in boxes
+++ Power
+++ Communication
+++ Testing
++++ Test Communication (RC and 4G)
++++ Test Battery System
++++ Test Sensors


