++ 1.3 - **Administrative**
+++ 1.3.1 - Project charter <<done>>
+++ 1.3.2 - Project plan <<started>>
+++ 1.3.3 - GANTT <<started>>
+++ 1.3.4 - SWOT <<started>>
+++ 1.3.5 - Presentation (5min) <<done>>
+++ 1.3.6 - Time report <<started>>
+++ 1.3.7 - Budget
+++ 1.3.8 - PERT <<started>>
+++ 1.3.9 - MoSCoW <<done>>
+++ 1.3.10 - Risk Anaysis <<started>>
++++ 1.3.10.1 - Product level <<done>>
++++ 1.3.10.2 - Project level 
