@startwbs ABSWBS
' !include style.puml
<style>
  wbsDiagram {
    Linecolor DimGray
    BackgroundColor White
    RoundCorner 10
    Margin 15
    Shadowing 0
    LineThickness 3
    MaximumWidth 200
    MinimumWidth 100

    :depth(0) {
      padding 10
      FontSize 20
      HorizontalAlignment center
    }
    :depth(1) {
      HorizontalAlignment center
    }
    :depth(2) {
      MaximumWidth 200
      MinimumWidth 100
    }
    .done{
      BackgroundColor LawnGreen
    }
    .failed{
      BackgroundColor Salmon
    }
    legend {
      FontSize 16
      Margin 10
      BackGroundColor White
      LineThickness 0
    }
  }
</style>


+ 1 AutoSail 2021

!include 1-software.puml

!include 2-hardware.puml

!include 3-dependable.puml

!include 4-administrative.puml



footer Designer: Simon Svensson

legend
|  <#LawnGreen>   Completed   |  <#Salmon>   Failed   |
endlegend

@endwbs
